/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DAC_1.h"
#include "Opamp_1.h"
#include "P0_1_aliases.h"
#include "P0_1.h"
#include "Opamp_2.h"
#include "P0_0_aliases.h"
#include "P0_0.h"
#include "Opamp_3.h"
#include "P3_6_aliases.h"
#include "P3_6.h"
#include "Opamp_4.h"
#include "P3_7_aliases.h"
#include "P3_7.h"
#include "DAC_2.h"
#include "DAC_3.h"
#include "ADC.h"
#include "P3_0_aliases.h"
#include "P3_0.h"
#include "Pin_12_0_aliases.h"
#include "Pin_12_0.h"
#include "P2_0_aliases.h"
#include "P2_0.h"
#include "P2_1_aliases.h"
#include "P2_1.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

