/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PGA.h"
#include "Sample_Hold.h"
#include "ADC.h"
#include "VDAC8.h"
#include "Comp.h"
#include "PWM.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "Pin3_5_aliases.h"
#include "Pin3_5.h"
#include "Pin3_1_aliases.h"
#include "Pin3_1.h"
#include "Pin5_1_aliases.h"
#include "Pin5_1.h"
#include "Pin12_5_aliases.h"
#include "Pin12_5.h"
#include "Pin1_4_aliases.h"
#include "Pin1_4.h"
#include "Pin12_6_aliases.h"
#include "Pin12_6.h"
#include "Pin2_7_aliases.h"
#include "Pin2_7.h"
#include "Pin3_0_aliases.h"
#include "Pin3_0.h"
#include "LCD.h"
#include "P3_7_aliases.h"
#include "P3_7.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

